### ISSUE TITLE
javascript `new Set()` instead of an empty array?

### ISSUE THREAD

**Issue by frederikhors** [keenethics/svelte-notifications#15]
Why don't you use javascript `new Set()` instead of an empty array?

**Comment by rationalquality** [comment]
@frederikhors, what are the advantages?

**Comment by frederikhors** [comment]
Native methods like .had, .add, .delete.

**Comment by rationalquality** [comment]
`new Set()` has a limited number of features. Much smaller than the array.

I want to use a simple method to remove one item from the array, but in the case of new Set() it's not so simple. 

If you know how to implement this, please make a pull request and show your implementation option.

Anyway thanks for your issue.
