### ISSUE TITLE
Passing class property to the notification component.

### ISSUE THREAD

**Issue by klikkn** [keenethics/svelte-notifications#23]
I like your notification style in whole, but I want to change color in some cases. e.g. error or success. So, I don't want to re-implement custom notification component as in example, I just want to pass the class.

**Comment by rationalquality** [comment]
@klikkn, added custom class in this [commit](https://github.com/keenethics/svelte-notifications/commit/73e27f5e9eb4a353c02f35eb3717519d0daabf2c). These changes will be in the next version.
