### ISSUE TITLE
Create add notification wrapper

### ISSUE THREAD

**Issue by dantium** [keenethics/svelte-notifications#27]
It's a bit of a problem to keep including the same position and removeAfter in addNotification when using it in many components. Really I want to just have these values in one place.

Is there some easy way to make a wrapper function for addNotification that would just take the text value for example?

**Comment by dantium** [comment]
I solved this by creating a component that adds a notification when when a store value is updated:

```javascript
<script>
    import { getNotificationsContext } from 'svelte-notifications';
    const { addNotification } = getNotificationsContext();
    import { message } from './stores.js';

    $: if ($message != '') {
        addNotification({
            text: $message,
            position: 'bottom-right',
            removeAfter: 4000
        });
    }
</script>
```

Not sure this is the best way to do it but it seems to work ok.

**Comment by rationalquality** [comment]
@dantium, it's good way if you want to handle only one method (only addNotification), but in other places (in other components) you still have to import your store with message. Correct me if I'm wrong
