### ISSUE TITLE
new parameter to choose how new notification are inserted if old ones still visible

### ISSUE THREAD

**Issue by ilrico** [keenethics/svelte-notifications#29]
Currently if notifications are in position top, new ones will appear under older ones.
And if position is bottom, it's the same, new ones will appear under older ones (moving up).  

Some devs would prefer to have new ones appearing above older ones when position is 'top' (same logic that current bottom: new ones come at the same entry position and older ones move)   

An additionnal parameters would be best to leave choice to developers. Such as "queue" { push, append } with push being current bottom behaviour (old ones moving to leave space for new one) and append leave old notifications unchanged, new one being added (current top behaviour)

**Comment by rationalquality** [comment]
I think you can try this solution: https://arthurclemens.github.io/dialogic/svelte/index.html?ref=madewithsvelte.com

**Comment by ilrico** [comment]
hum not really. idea is to have several notifications on screen, with choice in order display depending location, not to delay new ones.

**Comment by rationalquality** [comment]
Oh, I completely inattentively read your message. Yes, it’s worth considering this proposal. As soon as I have time, I will try to implement this.

**Comment by rationalquality** [comment]
Right now I'm working on a version where I add this feature. This implementation will not be in the current version of the package
