### ISSUE TITLE
Allow nested Notification Contexts

### ISSUE THREAD

**Issue by northkode** [keenethics/svelte-notifications#30]
Allow nested Notifications contexts by passing in a context unique ID into the 
`Notifications` Component instead of importing a generic:
`const context` in the context.js file. 

This will allow for different components to place notifications in different places of the app like top of a modal, or a root context for root global notifications etc

**Comment by rationalquality** [comment]
Now I'm busy developing a new version. There will be no context in it, therefore I have to close the issue. Sorry
