### ISSUE TITLE
Notifications appearance idea

### ISSUE THREAD

**Issue by loversandcode** [keenethics/svelte-notifications#31]
Sometimes I see that svelte-notification container overlap existing page content. For example if I call some addNotification() method and after that call clearNotifications(), and I have some button on bottom-right corner it becomes unclickable, cause notification container still present on the page.  

I don't think that it's a critical bug or something, but I suggest that it could be hidden in some way, to prevent this behaviour.

How should I avoid this thing? Maybe make custom Notification object? Or maybe this behavior(hiding container when it is not busy showing notifications) can be implemented?

**Comment by rationalquality** [comment]
Thanks for the description of this problem. I'll check it a bit later.

You can help me with this issue if provide some screenshots from your browser's inspector because I can't reproduce this problem on my demo site
