### ISSUE TITLE
Error importing lib

### ISSUE THREAD

**Issue by khalld** [keenethics/svelte-notifications#36]
Hi everyone, is not the first time that i use this library but now it's impossible instantiate the lib.

In a simple sapper/svelte project I import on my page:

```
  import { getNotificationsContext } from 'svelte-notifications';
  const { addNotification } = getNotificationsContext();
```

Suddently, when I instantiate a simple object used by that library (everywhere in the code) like

```
addNotification({
        text: 'OK!',
        position: 'bottom-right',
        type: 'success',
        removeAfter: 5000
});
```

I receive this message from the console

```
Uncaught (in promise) TypeError: Cannot destructure property 'addNotification' of 'getNotificationsContext(...)' as it is undefined.
```

What i suppose to do?

**Comment by johndstanhope** [comment]
Can you provide your parent and child components?

Here's a working REPL with your example:
https://svelte.dev/repl/bd27cf30acc7477d9c072846b3bfd6c3?version=3.17.2

You have to wrap your parent component with `<Notifications>`, where you're importing the library.

**Comment by AntouanK** [comment]
I have the same error.
I tried many combinations, it always returns `undefined`.

**Comment by AntouanK** [comment]
an example of what I tried

https://svelte.dev/repl/83ef439bc30c4e8aa72dfce1e4102f7a?version=3.17.2

I think the issue is that I create a modal on run-time and it's not "wrapped properly" with that Notifications.
But no clue on how to fix it.

**Comment by AntouanK** [comment]
this one also is not working

https://svelte.dev/repl/d11962a65b334a108e179c44c1be8f92?version=3.17.2

**Comment by rationalquality** [comment]
@khalld Wrong order of components. You can only call `getNotificationsContext` on a child component that has been wrapped in `Notification` component.

None of the examples do this correctly
