### ISSUE TITLE
Setting z-index on .default-position-style-* element

### ISSUE THREAD

**Issue by dkzlv** [keenethics/svelte-notifications#37]
**Is your feature request related to a problem? Please describe.**
I have some elements with a set `z-index`, that makes them overlay toasts. The only way to fix this is to set `z-index` manually on the container element inside `Notifications.svelte`.

**Describe the solution you'd like**
It would be fine for me to either have a css variable, that can be set externally (especially given the fact that css vars are going to be first-class citizens in Svelte soon enough), or just a good old prop would work as well.

**Describe alternatives you've considered**
For now I use a snippet like this:

```css
:global(.default-position-style-bottom-right) {
  z-index: 50;
}
```

I don't like this mainly cause I need to hardcode library's classnames, which is a bad practice.

**Additional context**
Can drop a PR if needed.

**Comment by hakimzulkufli** [comment]
I second this. I do have other elements that are using z-index as well due to the nature of its animations and transitions. It would be if the package have a prop to attach CSS classes onto the `<Notifications></Notifications>` tag.

**Comment by tarasowski** [comment]
Having the same issue as well. Mainly using the same method like @dkzlv

**Comment by mapkbalaji** [comment]
@usernamus Hi, how did you complete this issue? What is the solution for this?
