### ISSUE TITLE
the component does not work with snowpack

### ISSUE THREAD

**Issue by danielabenton** [keenethics/svelte-notifications#39]
**Describe the bug**
The component does not work with snowpack. Snowpack gets stuck with message: "installing dependencies...".

**To Reproduce**
1. Create a new svelte/snowpack app with the following code:
npx create-snowpack-app new-dir --template @snowpack/app-template-svelte

2. install the svelte-notifications with:
npm install svelte-notifications

3. in the src\index.js add an import statement for the component:

import App from "./App.svelte";
+ import Notifications from "svelte-notifications";

let app = new App({
  target: document.body,
});
...

4. run the app with:
npm start

5. snowpack starts and displays "installing dependencies..." but the installation seems to get stuck. Apparently, the component cannot be translated to EC module.

**Expected behavior**
It should be possible to use the component with snowpack.

**Screenshots** 
![problem](https://user-images.githubusercontent.com/75760259/101698661-2ff5ef80-3a7a-11eb-9574-05851705bbb4.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: FireFox 
 - Version 83.0 (64-bit)

**Additional context**
None.

**Comment by rationalquality** [comment]
Sorry for such a long wait. I'll try to reproduce your example as soon as possible.

**Comment by rationalquality** [comment]
For now, I don't know what to do with it. Reopen if problem persists
