### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by shaozi** [keenethics/svelte-notifications#47]
**Describe the bug**
When using typescript, `addNotification()` definition does not take argument. so on VSCode, it shows errors.

**To Reproduce**
```javascript
<script lang="ts">
  import { getNotificationsContext } from 'svelte-notifications'
  const { addNotification } = getNotificationsContext()

  // VScode shows errors: Expected 0 arguments, but got 1.ts(2554)
  addNotification({
          text: 'TestCase created',
          type: 'success',
          position: 'top-right',
          removeAfter: 2000
        })

```

**Expected behavior**
Should be no error

**Screenshots**

![Screen Shot 2021-07-13 at 11 05 55 AM](https://user-images.githubusercontent.com/417833/125488886-c898baf5-bbb6-465d-82be-59ea51c561d1.png)
![Screen Shot 2021-07-13 at 11 06 03 AM](https://user-images.githubusercontent.com/417833/125488891-13e87f3c-a0d5-4811-beb4-174e59921520.png)

**Comment by shaozi** [comment]
Another problem is that when using `<Notifications>` in `.svelte` file, it is highlighted as error: `JSX element type Notifications does not have any construct or call signatures `.

I modified the `types.d.ts` like this to fix both errors:

```typescript

export default class Notifications extends SvelteComponent {
    $$prop_def: NotificationsProps;
}

export function getNotificationsContext(): {
    subscribe: any;
    addNotification: addNotification;
    removeNotification: removeNotification;
    clearNotifications: clearNotifications;
};
```

Do you need a pull request?

**Comment by shaozi** [comment]
pull request: https://github.com/keenethics/svelte-notifications/pull/49

**Comment by apirogov** [comment]
I also have this JSX element error! Would be happy if the fix would be merged!

**Comment by shaozi** [comment]
Seems it is already merged. Did you test to see if it fix your JSX error?

**Comment by apirogov** [comment]
Ah right, and yes, the problem is solved! But it's not updated on npmjs.com. Would be great if a new version is released so I don't have to install from Github master branch!

**Comment by rationalquality** [comment]
@apirogov @shaozi I released a new version. If everything was fixed, please let me know so that I can close the issue
