### ISSUE TITLE
Error when using inside _layout.svelte

### ISSUE THREAD

**Issue by gigitalz** [keenethics/svelte-notifications#50]
**Describe the bug**
When using the notification tag inside _layout.svelte I get this error:

```
index.mjs:1218 Uncaught (in promise) Error: Cannot have duplicate keys in a keyed each
    at validate_each_keys (index.mjs:1218)
    at Object.update [as p] (Notifications.svelte? [sm]:70)
    at Object.update [as p] (Notifications.svelte? [sm]:68)
    at update (index.mjs:764)
    at flush (index.mjs:732)
```

**To Reproduce**
I am using svelte-kit routing system.

1. Use it inside _layout.svelte to wrap everything
2. Switch route and switch back
3. then try to launch a notification from within the switched back route tag

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version  92

**Comment by chris-aeviator** [comment]
I'm able to use Notifications with no issues inside my __layout.svelte

**Comment by doolijb** [comment]
The same issue, I have no problems if I'm only sending one notification.

```js
data.forEach( (entry, key) => { 
    entry.forEach( (error) => {
          addNotification({
              text: error,
              position: 'bottom-right',
              type: 'danger',
              removeAfter: 4000,
          })
    })
})
```

**Comment by doolijb** [comment]
Looked through the source.
Adding a unique id to each notification appears to resolve the error, though I consider it a bug.

**Comment by doolijb** [comment]
Opened pull request #51

**Comment by rationalquality** [comment]
@doolijb @gigitalz I released a new version. If everything was fixed, please let me know so that I can close the issue
