### ISSUE TITLE
Custom notification component example throws error in vscode

### ISSUE THREAD

**Issue by ghost** [keenethics/svelte-notifications#56]
I am using Svelte-kit with Typescript and tried the custom notification component from the README with the only difference that I have the <Notifications> component in the layout file. I am using version 0.9.93 of svelte-notifications.

The code seems to work, I can trigger the custom notification component but I get an error in vscode.

 Red error text under CustomNotification
`<Notifications item={CustomNotification}>`

If I hover over CustomNotification it logs the following to the vscode output:
`Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: EISDIR: illegal operation on a directory, read
  Code: -32603 `

The hover text says:
`Type 'typeof CustomNotification__SvelteComponent_' is missing the following properties from type 'SvelteComponentDev': $set, $on, $destroy, $$prop_def, and 5 more.`

**Comment by enriquecastill0** [comment]
Were you able to solve this? I'm having the same issue

**Comment by ghost** [comment]
No, I never found a solution. I just ignore the warning for now and the code does work. I will re-open the issue and hopefully someone knows or can fix.
