### ISSUE TITLE
Add `wrapper` prop to provider

### ISSUE THREAD

**Issue by dextermb** [keenethics/svelte-notifications#57]
Due to how styles are not inherited when set outside of a component it would be great if we could pass in a customer "wrapper" component similar to how a custom item can be provided.

```jsx
<Notifications wrapper={NotificationWrapper} item={NotificationItem}>
	<slot />
</Notifications>
```

When working on a mobile-first website the notifications are way-way-way too small to be useful.

<img width="389" alt="image" src="https://user-images.githubusercontent.com/6137789/155499591-dc2a79a2-509a-462f-b649-7c8e4ea83a74.png">

_This is an iPhone SE._

**Comment by rationalquality** [comment]
Right now I'm working on a version where I fixed this issue. Unfortunately, we will have to wait a bit with the release.

Try fixing this look by redefining the container rules via styles. The main problem here: `transform: translateX(-50%);`
