### ISSUE TITLE
Default values and type checking

### ISSUE THREAD

**Issue by rationalquality** [keenethics/svelte-notifications#6]
Now we have no default values and type checking ​​in the object that we use when creating the notification.

```javascript
{
  id: String, default value: new Date(),
  text: String, required,
  removeAfter: Number, optional,
  position: String, one of: ['top-left', 'top-center', 'top-right', 'bottom-left', 'bottom-center', 'bottom-right']
}
```

**Comment by Notalama** [comment]
@usernamus Should the "position" property be set as 'top-left' by default?

**Comment by rationalquality** [comment]
> @usernamus Should the "position" property be set as 'top-left' by default?

`bottom-center`

**Comment by rationalquality** [comment]
@Notalama good work at this!
