### ISSUE TITLE
Allow adding notifications outside of a component

### ISSUE THREAD

**Issue by phpfs** [keenethics/svelte-notifications#60]
Hi there,

first thing first: thank you very much for building this beautiful package :)

Besides adding notifications from within a component, it would be great to also be able to do this from within an asynchronous function somewhere outside of a component. Is this possible already? At least I currently receive an error message stating that I called `getNotificationsContext()` outside of a component...

Best, phpfs

**Comment by rationalquality** [comment]
Thanks a lot.

You need to follow the context. You will not be able to add notifications from a component that is not a child of the context.

Right now I'm working on a version where I deleted context at all. Just render `Notifications` component and use `addNotification` function from anywhere.

Now it is in closed development. But hopefully there will be a release soon.
