### ISSUE TITLE
Custom Notifications Not Working

### ISSUE THREAD

**Issue by emrahaydemir** [keenethics/svelte-notifications#67]
Hi, im trying to add notifications on my project. Default notifications working but customs not. I tried on Svelte REPL but still not working.

[https://svelte.dev/repl/a58c00f71ed640b6855c682ddb7ac518?version=3.50.1](https://svelte.dev/repl/a58c00f71ed640b6855c682ddb7ac518?version=3.50.1)

**Comment by rationalquality** [comment]
Found the cause of the issue. I will release a patch soon

**Comment by rationalquality** [comment]
Released version 0.9.98 with changes. The whole point was that the `text` field was required even for a custom component
